# Generated by Django 2.2.1 on 2019-08-02 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190728_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 23, 52, 58, 206421)),
        ),
    ]
